


ALTER TABLE brand MODIFY COLUMN image VARCHAR(255);


ALTER TABLE category MODIFY COLUMN image VARCHAR(255);


ALTER TABLE product MODIFY COLUMN thumbnail VARCHAR(255);


ALTER TABLE product_review MODIFY COLUMN image VARCHAR(255);

ALTER TABLE vendor_product_image MODIFY COLUMN image VARCHAR(255);


